# Generated by Django 3.2.4 on 2021-06-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('petname', models.CharField(max_length=20)),
                ('petimage', models.ImageField(upload_to='')),
                ('petkind', models.CharField(max_length=30)),
                ('pettype', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=200)),
                ('whereCD', models.CharField(max_length=200)),
                ('whereCGG', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('money', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_app.pet')),
            ],
        ),
    ]
