# Generated by Django 3.2.4 on 2021-06-17 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sil_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('petname', models.CharField(max_length=20)),
                ('petimage', models.ImageField(null=True, upload_to='board_app')),
                ('petkind', models.CharField(max_length=30)),
                ('pettype', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=200)),
                ('whereCD', models.CharField(max_length=200)),
                ('whereCGG', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('money', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
