# Generated by Django 3.2.4 on 2021-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_auto_20210617_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sil_board',
            name='petimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
