# Generated by Django 3.2.4 on 2021-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_alter_sil_board_petimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sil_board',
            name='petage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
