# Generated by Django 3.2.4 on 2021-06-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sil_board',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='cdate',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='cpost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='cuser',
        ),
    ]
